alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gco="git checkout"
alias gap="git add --patch"
alias gb="git branch"
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gd="git diff"
alias gds="git diff --cached"
